export const GET_ALL_PEOPLE = 'GET_ALL_PEOPLE';
export const GET_PERSON_DETAILS = 'GET_PERSON_DETAILS';
export const GET_CHARACTER_HOMEWORLD = 'GET_CHARACTER_HOMEWORLD';
export const GET_HOMEWORLD_FILMS = 'GET_HOMEWORLD_FILMS';
export const GET_HOMEWORLD_RESIDENTS = 'GET_HOMEWORLD_RESIDENTS';
export const GET_CHARACTER_FILMS = 'GET_CHARACTER_FILMS';
